site_name: Imperium Repo Wiki
site_author: giosuel
site_url: https://giosuel.github.io/imperium-repo
site_description: The official Imperium Repo wiki. A powerful and highly performant all-in-one debugging tool to test and explore game mechanics and functionality in R.E.P.O.

repo_name: giosuel/imperium-repo
repo_url: https://github.com/giosuel/imperium-repo

nav:
 - Home: 'index.md'
 - Quick Start: 'quick-start.md'
 - Imperium API:
    - 'api/index.md'
    - Visualization API:
      - Static Visualizers: 'api/visualization/static.md'
      - Insights: 'api/visualization/insights.md'
    - Portal API: 'api/portal.md'
    - Event Log API: 'api/event-log.md'
    - World API: 'api/world.md'
 - Issues: 'https://github.com/giosuel/imperium-repo/issues/'

theme:
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.top
    - navigation.tabs
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - toc.follow
    - content.tooltips
    - navigation.indexes
    - content.footnote.tooltips

  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  logo: https://github.com/giosuel/imperium-repo/blob/development/assets/icon_256x256.png?raw=true
  favicon: https://github.com/giosuel/imperium-repo/blob/development/assets/icon_256x256.png?raw=true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - offline
  - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8

extra_css:
  - stylesheets/extra.css