[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "giosuel"
name = "Imperium_Repo"
description = "Imperium is a powerful and highly performant all-in-one debugging tool and creative mode to test and explore game mechanics and functionality in R.E.P.O. "
websiteUrl = "https://github.com/giosuel/Imperium"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Utility-UnityExplorer = "4.12.3"
Rune580-REPO_SteamNetworking_Lib = "0.1.0"
Zehs-REPOLib = "2.1.0"
giosuel-Librarium = "0.0.4"
DiFFoZ-BepInEx_MonoMod_Debug_Patcher = "1.1.1"

[build]
icon = "assets/icon_256x256.png"
readme = "README.md"
outdir = "artifacts/thunderstore/"

[[build.copy]]
source = "artifacts/bin/Imperium/release/giosuel.Imperium.dll"
target = "/"

[[build.copy]]
source = "CHANGELOG.md"
target = "/"

[[build.copy]]
source = "LICENSE"
target = "/"

[publish]
communities = ["repo"]

[publish.categories]
repo = ["mods", "tools", "serverside", "clientside", "libraries", "misc"]