[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "giosuel"
name = "Imperium"
description = "Imperium is a powerful and highly performant all-in-one debugging tool to test and explore game mechanics and functionality in R.E.P.O. "
websiteUrl = "https://github.com/giosuel/Imperium"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "assets/icon.png"
readme = "README.md"
outdir = "artifacts/thunderstore/"

[[build.copy]]
source = "artifacts/bin/Imperium/release/giosuel.Imperium.dll"
target = "/"

[[build.copy]]
source = "CHANGELOG.md"
target = "/"

[[build.copy]]
source = "LICENSE"
target = "/"

[publish]
communities = ["repo"]

[publish.categories]
repo = ["mods", "tools", "serverside", "clientside", "libraries", "misc"]